// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type Ingredient struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	ProductID int    `json:"productID"`
}

type NewIngredient struct {
	Name string `json:"name"`
}

type NewProduct struct {
	Name  string  `json:"name"`
	Price *string `json:"price"`
}

type Product struct {
	ID          int          `json:"id"`
	Name        string       `json:"name"`
	Price       string       `json:"price"`
	Ingredients []Ingredient `json:"ingredients"`
}

func FetchConnection() *gorm.DB {
	db, err := gorm.Open("mysql", "user:user123@(localhost)/gqltest?charset=utf8&parseTime=True&loc=Local")
	if err != nil {
		panic(err)
	}
	return db
}
